### ISSUE TITLE
 ERROR Could not find product ls8_usgs_wofs_scene in datacube

### ISSUE THREAD

**Issue by dunkgray** [opendatacube/WOFLs-orchestration#5]
wofs didn't like the product change to ls_usgs_wofs_scene
2019-08-02 04:35:02,864 INFO Writing file: ./LT05_WATER_164067_19900816_20170130_01_T1_raw.tiff
Reading input: LT05_WATER_164067_19900816_20170130_01_T1_raw.tiff
  [####################################]  100%             
Adding overviews...
Updating dataset tags...
Writing output to: LT05_WATER_164067_19900816_20170130_01_T1_water.tiff
2019-08-02 04:35:07,182 WARNING CPLE_NotSupported in driver GTiff does not support creation option NODATA
2019-08-02 04:35:28,607 INFO Creating metadata file
2019-08-02 04:35:28,609 ERROR Could not find product ls8_usgs_wofs_scene in datacube
Traceback (most recent call last):
  File "/usr/local/bin/watch-queue.py", line 124, in <module>
    int(MAX_JOB_PER_WORKER))
  File "/usr/local/bin/watch-queue.py", line 89, in processing_loop
    run.main(key)
  File "/opt/scripts/run.py", line 463, in main
    './WATER_METADATA.yaml'
  File "/opt/scripts/run.py", line 328, in _create_metadata_file
    extent=extent, center_time=center_time, uri=uri
  File "/usr/local/lib/python3.6/dist-packages/datacube-1.7+19.gd3944f00.dirty-py3.6.egg/datacube/model/utils.py", line 206, in make_dataset
    merge(document, product.metadata_doc)
AttributeError: 'NoneType' object has no attribute 'metadata_doc'

**Comment by dunkgray** [comment]
fixed
To github.com:opendatacube/WOFLs-orchestration.git
   31e2359..30881fc  dsg_landsat_usgs_testing -> dsg_landsat_usgs_testing
